methods:
     1:
       algorithm: "rb_ipop_cma_esr_ppmf"
       params: 
        - "last_its_type"
        - "p_target"
       values:
        - "ave"
        - 0.2
ids:
  - "ppmf-br-ave"
probnum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
dims:
  - 10
  - 20
cec: 21
repnum: 30
suite: "bias_rot"
cpupc: 0.75
source: "~/cec2020/R"
dest: "~/cec2020/data/final"
