methods:
     1:
       algorithm: "rb_ipop_cma_esr_sppmf"
       params: 
        - "last_its_type"
        - "p_target"
        - "c_ps"
       values:
        - "ave"
        - 0.2
        - 0.1
      2:
       algorithm: "rb_ipop_cma_esr_sppmf"
       params: 
        - "last_its_type"
        - "p_target"
        - "c_ps"
       values:
        - "ave"
        - 0.2
        - 0.3
      3:
       algorithm: "rb_ipop_cma_esr_sppmf"
       params: 
        - "last_its_type"
        - "p_target"
        - "c_ps"
       values:
        - "ave"
        - 0.2
        - 0.6
ids:
  - "sppmf-b-ave"
probnum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
dims:
  - 10
cec: 21
repnum: 30
suite: "bias"
cpupc: 0.75
source: "~/cec2020/R"
dest: "~/cec2020/data/final"
